/**:
  ros__parameters:
    filter_target_label:
      UNKNOWN : true
      CAR : false
      TRUCK : false
      BUS : false
      TRAILER : false
      MOTORCYCLE : false
      BICYCLE : false
      PEDESTRIAN : false

    upper_bound_x: 100000.0
    lower_bound_x: -100000.0
    upper_bound_y: 100000.0
    lower_bound_y: -100000.0
