/**:
  ros__parameters:
      devices: ["enp2s0f1"]
      traffic_reader_port: 7636
      monitor_program: "*"
      crc_error_check_duration: 1
      crc_error_count_threshold: 1
      reassembles_failed_check_duration: 1
      reassembles_failed_check_count: 1
