/**:
  ros__parameters:
    # Waiting periods after longitudinal velocity become zero to ensure the vehicle is completely stopped
    # default value 50, assuming the frequency of topic velocity_status is 50Hz 
    num_wait_period: 0

    # frames of main lidar used for mapping
    total_count: 5

    # save calib results to 
    save_path: "./"

    # save calib results file
    file_res: "calib_res.csv"

    # save calib pcd file
    file_pcd: "result_with_sub_lidar.pcd"

    # Topic for main lidar
    main_lidar_topic: "/sensing/lidar/top/rectified/pointcloud_ex"

    # Topic for sub lidar
    sub_lidar_topic: "/sensing/lidar/right/rectified/pointcloud_ex"

    # Topic for velocity status
    velocity_status_topic: "/vehicle/status/velocity_status"

    # Initial transformation vector (x, y, z, roll, pitch, yaw), where euler angles are in rad 
    #trans_vector: [2.5, 0.0, -1.2, 0.0, 0.0, 0.0]
    # # Initial transformation in translation and rotation
    translation: [-1.226, 5.055, -0.388]
    rotation: 
      [ 
        0.00079633, 0.79909951, -0.60119825,
        -0.99999968, 0.00063634, -0.00047875,
        -0.00000000, 0.60119844, 0.79909977
      ]
    # # Initial transformation matirx from sub lidar to main lidar
    # trans_matirx: [ 
    #     1.0,  0.0,  0.0,  0.0,
    #     0.0, 1.0,  0.0,  0.0,
    #     0.0,  0.0, 1.0,  0.0,
    #     0.0,  0.0,  0.0,  1.0
    #   ]
  
